[package]
name = "HBroker-ServerApp"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
config = "0.13"
warp = "0.3"
tokio = { version = "1", features = ["full"] }

HBank = { path = "../HBank" }

actix-web = "4.0"

async-trait = "0.1.81"